import React from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Heart, Home, Search, CalendarDays, Settings, Share2, Download, Moon, Sun, Save, MessageCircle, Sparkles, Flame, Compass, ShieldCheck, ExternalLink } from 'lucide-react';
import './styles.css';

type Tab = 'hoy' | 'biblia' | 'sentir' | 'buscar' | 'planes' | 'oracion' | 'guardado' | 'ajustes' | 'instalar' | 'compartir';
type Verse = { id: string; book: string; chapter: number; verse: number; text: string; testament: 'Antiguo Testamento' | 'Nuevo Testamento'; theme: string[] };
type Note = { verseId: string; text: string; updatedAt: string };

const verses: Verse[] = [
  { id: 'gen-1-1', book: 'Génesis', chapter: 1, verse: 1, testament: 'Antiguo Testamento', text: 'EN el principio crió Dios los cielos y la tierra.', theme: ['comienzo','fe'] },
  { id: 'sal-23-1', book: 'Salmos', chapter: 23, verse: 1, testament: 'Antiguo Testamento', text: 'Jehová es mi pastor; nada me faltará.', theme: ['paz','cuidado'] },
  { id: 'sal-27-1', book: 'Salmos', chapter: 27, verse: 1, testament: 'Antiguo Testamento', text: 'Jehová es mi luz y mi salvación: ¿de quién temeré?', theme: ['miedo','valentia'] },
  { id: 'sal-34-18', book: 'Salmos', chapter: 34, verse: 18, testament: 'Antiguo Testamento', text: 'Cercano está Jehová á los quebrantados de corazón.', theme: ['tristeza','duelo'] },
  { id: 'sal-46-1', book: 'Salmos', chapter: 46, verse: 1, testament: 'Antiguo Testamento', text: 'Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.', theme: ['proteccion','miedo'] },
  { id: 'sal-91-2', book: 'Salmos', chapter: 91, verse: 2, testament: 'Antiguo Testamento', text: 'Diré yo á Jehová: Esperanza mía, y castillo mío; mi Dios, en él confiaré.', theme: ['proteccion','esperanza'] },
  { id: 'prov-3-5', book: 'Proverbios', chapter: 3, verse: 5, testament: 'Antiguo Testamento', text: 'Fíate de Jehová de todo tu corazón, y no estribes en tu prudencia.', theme: ['decision','direccion'] },
  { id: 'prov-16-3', book: 'Proverbios', chapter: 16, verse: 3, testament: 'Antiguo Testamento', text: 'Encomienda á Jehová tus obras, y tus pensamientos serán afirmados.', theme: ['futuro','trabajo'] },
  { id: 'isa-40-31', book: 'Isaías', chapter: 40, verse: 31, testament: 'Antiguo Testamento', text: 'Mas los que esperan á Jehová tendrán nuevas fuerzas.', theme: ['cansancio','animo'] },
  { id: 'isa-41-10', book: 'Isaías', chapter: 41, verse: 10, testament: 'Antiguo Testamento', text: 'No temas, porque yo soy contigo; no desmayes, porque yo soy tu Dios.', theme: ['soledad','miedo'] },
  { id: 'mat-5-9', book: 'Mateo', chapter: 5, verse: 9, testament: 'Nuevo Testamento', text: 'Bienaventurados los pacificadores: porque ellos serán llamados hijos de Dios.', theme: ['enojo','paz'] },
  { id: 'mat-6-34', book: 'Mateo', chapter: 6, verse: 34, testament: 'Nuevo Testamento', text: 'Así que, no os congojéis por el día de mañana.', theme: ['ansiedad','futuro'] },
  { id: 'mat-11-28', book: 'Mateo', chapter: 11, verse: 28, testament: 'Nuevo Testamento', text: 'Venid á mí todos los que estáis trabajados y cargados, que yo os haré descansar.', theme: ['cansancio','descanso'] },
  { id: 'juan-8-12', book: 'Juan', chapter: 8, verse: 12, testament: 'Nuevo Testamento', text: 'Yo soy la luz del mundo: el que me sigue, no andará en tinieblas.', theme: ['direccion','fe'] },
  { id: 'juan-14-27', book: 'Juan', chapter: 14, verse: 27, testament: 'Nuevo Testamento', text: 'La paz os dejo, mi paz os doy: no como el mundo la da, yo os la doy.', theme: ['paz','ansiedad'] },
  { id: 'rom-8-28', book: 'Romanos', chapter: 8, verse: 28, testament: 'Nuevo Testamento', text: 'Y sabemos que á los que á Dios aman, todas las cosas les ayudan á bien.', theme: ['esperanza','proceso'] },
  { id: 'rom-12-2', book: 'Romanos', chapter: 12, verse: 2, testament: 'Nuevo Testamento', text: 'Y no os conforméis á este siglo; mas reformaos por la renovación de vuestro entendimiento.', theme: ['jovenes','proposito'] },
  { id: '1cor-13-4', book: '1 Corintios', chapter: 13, verse: 4, testament: 'Nuevo Testamento', text: 'La caridad es sufrida, es benigna; la caridad no tiene envidia.', theme: ['amor','familia'] },
  { id: '2cor-5-17', book: '2 Corintios', chapter: 5, verse: 17, testament: 'Nuevo Testamento', text: 'De modo que si alguno está en Cristo, nueva criatura es.', theme: ['nuevo','culpa'] },
  { id: 'gal-6-9', book: 'Gálatas', chapter: 6, verse: 9, testament: 'Nuevo Testamento', text: 'No nos cansemos, pues, de hacer bien; que á su tiempo segaremos, si no hubiéremos desmayado.', theme: ['perseverancia','desmotivado'] },
  { id: 'fil-4-6', book: 'Filipenses', chapter: 4, verse: 6, testament: 'Nuevo Testamento', text: 'Por nada estéis afanosos; sino sean notorias vuestras peticiones delante de Dios en toda oración y ruego.', theme: ['ansiedad','oracion'] },
  { id: 'fil-4-13', book: 'Filipenses', chapter: 4, verse: 13, testament: 'Nuevo Testamento', text: 'Todo lo puedo en Cristo que me fortalece.', theme: ['animo','jovenes'] },
  { id: 'col-3-23', book: 'Colosenses', chapter: 3, verse: 23, testament: 'Nuevo Testamento', text: 'Y todo lo que hagáis, hacedlo de ánimo, como al Señor, y no á los hombres.', theme: ['trabajo','proposito'] },
  { id: '1tim-4-12', book: '1 Timoteo', chapter: 4, verse: 12, testament: 'Nuevo Testamento', text: 'Ninguno tenga en poco tu juventud; pero sé ejemplo de los fieles.', theme: ['jovenes','identidad'] },
  { id: 'heb-11-1', book: 'Hebreos', chapter: 11, verse: 1, testament: 'Nuevo Testamento', text: 'Es pues la fe la sustancia de las cosas que se esperan, la demostración de las cosas que no se ven.', theme: ['fe','esperanza'] },
  { id: 'sant-1-5', book: 'Santiago', chapter: 1, verse: 5, testament: 'Nuevo Testamento', text: 'Y si alguno de vosotros tiene falta de sabiduría, demándela á Dios.', theme: ['decision','sabiduria'] },
  { id: '1ped-5-7', book: '1 Pedro', chapter: 5, verse: 7, testament: 'Nuevo Testamento', text: 'Echando toda vuestra solicitud en él, porque él tiene cuidado de vosotros.', theme: ['ansiedad','cuidado'] },
  { id: '1juan-1-9', book: '1 Juan', chapter: 1, verse: 9, testament: 'Nuevo Testamento', text: 'Si confesamos nuestros pecados, él es fiel y justo para que nos perdone nuestros pecados.', theme: ['perdon','culpa'] },
  { id: 'apoc-21-4', book: 'Apocalipsis', chapter: 21, verse: 4, testament: 'Nuevo Testamento', text: 'Y limpiará Dios toda lágrima de los ojos de ellos.', theme: ['duelo','esperanza'] }
];

const allBooks = ['Génesis','Éxodo','Levítico','Números','Deuteronomio','Josué','Jueces','Rut','1 Samuel','2 Samuel','1 Reyes','2 Reyes','1 Crónicas','2 Crónicas','Esdras','Nehemías','Ester','Job','Salmos','Proverbios','Eclesiastés','Cantar de los Cantares','Isaías','Jeremías','Lamentaciones','Ezequiel','Daniel','Oseas','Joel','Amós','Abdías','Jonás','Miqueas','Nahum','Habacuc','Sofonías','Hageo','Zacarías','Malaquías','Mateo','Marcos','Lucas','Juan','Hechos','Romanos','1 Corintios','2 Corintios','Gálatas','Efesios','Filipenses','Colosenses','1 Tesalonicenses','2 Tesalonicenses','1 Timoteo','2 Timoteo','Tito','Filemón','Hebreos','Santiago','1 Pedro','2 Pedro','1 Juan','2 Juan','3 Juan','Judas','Apocalipsis'];

const moods = [
  { name: 'Ansiedad', verseIds: ['mat-6-34','fil-4-6','1ped-5-7'], text: 'Respirá. No tenés que cargar el futuro entero hoy.', prayer: 'Dios, te entrego lo que no puedo controlar.', action: 'Respirá lento y orá una frase simple.' },
  { name: 'Miedo', verseIds: ['sal-27-1','sal-46-1','isa-41-10'], text: 'El miedo grita, pero no manda sobre tu vida.', prayer: 'Señor, guardá mi mente y mi camino.', action: 'Nombrá tu miedo y entregáselo a Dios.' },
  { name: 'Tristeza', verseIds: ['sal-34-18','apoc-21-4','rom-8-28'], text: 'No estás exagerando. Lo que sentís importa, y Dios se acerca al corazón herido.', prayer: 'Señor, sosteneme en este momento.', action: 'Hablá con alguien que te quiera bien.' },
  { name: 'Cansancio', verseIds: ['mat-11-28','isa-40-31','gal-6-9'], text: 'No sos una máquina. También necesitás pausa y descanso.', prayer: 'Dios, renová mis fuerzas.', action: 'Tomá cinco minutos sin pantalla.' },
  { name: 'Culpa', verseIds: ['1juan-1-9','2cor-5-17','prov-3-5'], text: 'La culpa puede ser una señal para volver, no una cadena para quedarte tirado.', prayer: 'Dame humildad para pedir perdón y cambiar.', action: 'Elegí una acción concreta de reparación.' },
  { name: 'Soledad', verseIds: ['isa-41-10','sal-23-1','1ped-5-7'], text: 'Sentirte solo no significa estar abandonado.', prayer: 'Padre, haceme sentir tu compañía.', action: 'Mandale un mensaje a una persona segura.' },
  { name: 'Decisiones', verseIds: ['prov-3-5','sant-1-5','juan-8-12'], text: 'No todo se ve de una vez. A veces Dios guía paso a paso.', prayer: 'Dame sabiduría para elegir bien.', action: 'Anotá la decisión y lo más prudente.' },
  { name: 'Enojo', verseIds: ['mat-5-9','1cor-13-4','col-3-23'], text: 'No niegues el enojo, pero tampoco le entregues el volante.', prayer: 'Señor, ayudame a responder con dominio propio.', action: 'Esperá antes de contestar.' },
  { name: 'Jóvenes con propósito', verseIds: ['1tim-4-12','rom-12-2','fil-4-13'], text: 'Tu edad no te descalifica. Tu vida puede ser ejemplo desde ahora.', prayer: 'Dios, encendé propósito y carácter en mí.', action: 'Hacé hoy algo pequeño que te acerque a la persona que querés ser.' }
];

const plans = [
  { id: 'jovenes14', title: '14 días para jóvenes con propósito', days: ['1 Timoteo 4', 'Romanos 12', 'Filipenses 4', 'Proverbios 3'] },
  { id: 'ansiedad7', title: '7 días para bajar la ansiedad', days: ['Mateo 6', 'Filipenses 4', '1 Pedro 5', 'Juan 14'] },
  { id: 'nt90', title: 'Nuevo Testamento en 90 días', days: ['Mateo 1-2', 'Mateo 3-4', 'Mateo 5-6', 'Juan 1'] },
  { id: 'salmos30', title: 'Salmos en 30 días', days: ['Salmos 1-3', 'Salmos 4-6', 'Salmos 23', 'Salmos 91'] }
];
const prayers = [['Paz mental','Señor, calmá mis pensamientos y ayudame a vivir este día con claridad.'],['Familia','Dios, cuidá mi casa, saná lo que duele y enseñanos a escucharnos.'],['Futuro','Padre, guiá mis decisiones y ayudame a no desesperarme por lo que todavía no veo.'],['Perdón','Señor, dame humildad para reconocer errores y fuerza para cambiar.']];
const books = Array.from(new Set(verses.map(v => v.book)));
const todayVerse = verses[new Date().getDate() % verses.length];

function useLocal<T>(key: string, initial: T) { const [value, setValue] = React.useState<T>(() => { try { return JSON.parse(localStorage.getItem(key) || '') as T; } catch { return initial; } }); React.useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value]); return [value, setValue] as const; }
function Card({ children, className = '', onClick }: { children: React.ReactNode; className?: string; onClick?: () => void }) { return <section className={`card ${className}`} onClick={onClick}>{children}</section>; }
function Button({ children, onClick, variant = 'primary' }: { children: React.ReactNode; onClick?: () => void; variant?: 'primary' | 'ghost' }) { return <button className={`btn ${variant}`} onClick={onClick}>{children}</button>; }
function VerseCard({ verse, onSave, saved, onNote }: { verse: Verse; onSave: () => void; saved: boolean; onNote?: () => void }) { return <Card><p className="ref">{verse.book} {verse.chapter}:{verse.verse}</p><p className="verse">“{verse.text}”</p><div className="row wrap"><Button variant={saved ? 'ghost' : 'primary'} onClick={onSave}><Save size={16}/> {saved ? 'Guardado' : 'Guardar'}</Button>{onNote && <Button variant="ghost" onClick={onNote}>Nota</Button>}</div></Card>; }

function App() {
  const [tab, setTab] = React.useState<Tab>('hoy');
  const [theme, setTheme] = useLocal('pv-theme', 'dark');
  const [font, setFont] = useLocal('pv-font', 18);
  const [saved, setSaved] = useLocal<string[]>('pv-saved', []);
  const [notes, setNotes] = useLocal<Note[]>('pv-notes', []);
  const [progress, setProgress] = useLocal<Record<string, string[]>>('pv-progress', {});
  const [query, setQuery] = React.useState('');
  const [book, setBook] = React.useState(books[0]);
  const [selectedMood, setSelectedMood] = React.useState(moods[0]);
  React.useEffect(() => { document.body.dataset.theme = theme; document.documentElement.style.setProperty('--font-size', `${font}px`); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined); }, [theme, font]);
  const toggleSave = (id: string) => setSaved(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id]);
  const writeNote = (verseId: string) => { const current = notes.find(n => n.verseId === verseId)?.text || ''; const text = prompt('Escribí tu nota personal', current); if (text === null) return; setNotes(ns => [...ns.filter(n => n.verseId !== verseId), { verseId, text, updatedAt: new Date().toISOString() }]); };
  const moodVerses = (ids: string[]) => ids.map(id => verses.find(v => v.id === id)).filter(Boolean) as Verse[];
  const searchResults = verses.filter(v => { const q = query.toLowerCase().trim(); return !q || v.text.toLowerCase().includes(q) || v.book.toLowerCase().includes(q) || v.theme.some(t => q.includes(t) || t.includes(q)); });
  const shareApp = () => { const text = `Te comparto Palabra Viva, una app bíblica gratuita con palabra diaria, oración y lectura según cómo te sentís. ${location.href}`; if (navigator.share) navigator.share({ title: 'Palabra Viva', text, url: location.href }); else navigator.clipboard.writeText(text).then(() => alert('Link copiado')); };
  const shareVerse = () => navigator.share ? navigator.share({ title: 'Palabra para hoy', text: `${todayVerse.book} ${todayVerse.chapter}:${todayVerse.verse} — ${todayVerse.text}` }) : navigator.clipboard.writeText(todayVerse.text);
  return <main className="app"><header className="topbar"><div><span className="eyebrow">Palabra Viva</span><h1>{tab === 'hoy' ? 'Una palabra para hoy' : titleFor(tab)}</h1></div><button className="icon" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun/> : <Moon/>}</button></header>
    {tab === 'hoy' && <div className="stack"><section className="hero"><div className="pill"><Sparkles size={16}/> Devocional diario</div><h2>Fe clara para una generación con mil ruidos.</h2><p>Una palabra breve, real y compartible para empezar o cerrar el día.</p></section><Card className="today"><div className="row between"><p className="ref">{todayVerse.book} {todayVerse.chapter}:{todayVerse.verse}</p><Flame size={22}/></div><p className="verse big">“{todayVerse.text}”</p><p className="soft">No corras solo. Llevá esta palabra como una señal de calma, dirección y fe.</p><p><strong>Oración breve:</strong> Señor, hablame con claridad y ayudame a vivir este día con sabiduría.</p><div className="row wrap"><Button onClick={() => toggleSave(todayVerse.id)}>Guardar</Button><Button variant="ghost" onClick={shareVerse}><Share2 size={16}/> Compartir</Button><Button variant="ghost" onClick={() => setTab('instalar')}><Download size={16}/> Instalar</Button></div></Card><div className="grid2"><Card className="mini" onClick={() => setTab('sentir')}><Heart/> ¿Cómo venís?</Card><Card className="mini" onClick={() => setTab('buscar')}><Search/> Buscá una palabra</Card><Card className="mini" onClick={() => setTab('compartir')}><Share2/> Compartir app</Card><Card className="mini" onClick={() => setTab('planes')}><Compass/> Plan joven</Card></div></div>}
    {tab === 'biblia' && <div className="stack"><Card className="gradient"><h2>Biblia</h2><p>Esta versión ya tiene más versículos curados y la ruta legal para usar la Biblia completa Reina-Valera 1909.</p><Button variant="ghost" onClick={() => window.open('https://ebible.org/spaRV1909/', '_blank')}><ExternalLink size={16}/> Abrir Biblia completa RV1909</Button></Card><Card><p className="soft"><strong>Nota honesta:</strong> el texto completo offline todavía no está importado en JSON. No voy a inventarlo ni usar traducciones con copyright. La fuente legal preparada es RV1909 de dominio público.</p></Card><div className="chips">{books.map(b => <button className={book === b ? 'chip active' : 'chip'} onClick={() => setBook(b)} key={b}>{b}</button>)}</div>{verses.filter(v => v.book === book).map(v => <VerseCard key={v.id} verse={v} saved={saved.includes(v.id)} onSave={() => toggleSave(v.id)} onNote={() => writeNote(v.id)} />)}<Card><h3>Libros de la Biblia completa</h3><div className="bookgrid">{allBooks.map(b => <span key={b}>{b}</span>)}</div></Card></div>}
    {tab === 'sentir' && <div className="stack"><Card className="gradient"><h2>¿Cómo venís hoy?</h2><p>No tenés que ordenar todo ahora. Elegí cómo estás y leamos una palabra juntos.</p></Card><div className="chips">{moods.map(m => <button className={selectedMood.name === m.name ? 'chip active' : 'chip'} onClick={() => setSelectedMood(m)} key={m.name}>{m.name}</button>)}</div><Card><h3>{selectedMood.name}</h3><p>{selectedMood.text}</p><p><strong>Oración:</strong> {selectedMood.prayer}</p><p><strong>Una acción pequeña:</strong> {selectedMood.action}</p></Card>{moodVerses(selectedMood.verseIds).map(v => <VerseCard key={v.id} verse={v} saved={saved.includes(v.id)} onSave={() => toggleSave(v.id)} />)}<Card className="warning"><ShieldCheck/><p>Palabra Viva no reemplaza ayuda médica, psicológica, pastoral ni servicios de emergencia. Si estás en peligro, pensás hacerte daño o no podés mantenerte seguro, hablá ahora con una persona de confianza o comunicate con emergencias locales.</p></Card></div>}
    {tab === 'buscar' && <div className="stack"><Card><input className="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Ej: ansiedad, miedo, jóvenes, propósito, perdón..." /></Card>{searchResults.map(v => <VerseCard key={v.id} verse={v} saved={saved.includes(v.id)} onSave={() => toggleSave(v.id)} />)}</div>}
    {tab === 'planes' && <div className="stack">{plans.map(p => <Card key={p.id}><div className="row between"><h3>{p.title}</h3><span className="badge">{Math.round(((progress[p.id]?.length || 0) / p.days.length) * 100)}%</span></div>{p.days.map((d, i) => { const done = progress[p.id]?.includes(d); return <label className="check" key={d}><input type="checkbox" checked={!!done} onChange={() => setProgress(pr => ({...pr, [p.id]: done ? (pr[p.id] || []).filter(x => x !== d) : [...(pr[p.id] || []), d]}))}/><span>Día {i + 1}: {d}</span></label>; })}</Card>)}</div>}
    {tab === 'oracion' && <div className="stack">{prayers.map(([t, p]) => <Card key={t}><p className="ref">{t}</p><p>{p}</p></Card>)}</div>}
    {tab === 'guardado' && <div className="stack">{saved.length === 0 && <Card><p>Todavía no guardaste versículos. Cuando una palabra te hable, guardala acá.</p></Card>}{verses.filter(v => saved.includes(v.id)).map(v => <VerseCard key={v.id} verse={v} saved onSave={() => toggleSave(v.id)} onNote={() => writeNote(v.id)} />)}{notes.map(n => <Card key={n.verseId}><p className="ref">Nota personal</p><p>{n.text}</p></Card>)}</div>}
    {tab === 'instalar' && <div className="stack"><Card className="gradient"><h2>Instalá Palabra Viva</h2><p>Así te queda como app en el celular, sin buscar el link cada vez.</p></Card><Card><h3>Android</h3><ol><li>Abrí el link en Chrome.</li><li>Tocá los tres puntitos.</li><li>Tocá Instalar app o Agregar a pantalla principal.</li><li>Confirmá.</li></ol></Card><Card><h3>iPhone</h3><ol><li>Abrí el link en Safari.</li><li>Tocá Compartir.</li><li>Tocá Agregar a pantalla de inicio.</li><li>Confirmá.</li></ol></Card></div>}
    {tab === 'compartir' && <div className="stack"><Card className="gradient"><h2>Compartí una palabra</h2><p>Compartí Palabra Viva con alguien que necesite fe, paz o esperanza.</p><Button onClick={shareApp}><MessageCircle size={16}/> Compartir o copiar link</Button></Card></div>}
    {tab === 'ajustes' && <div className="stack"><Card><h3>Apariencia</h3><div className="row wrap"><Button onClick={() => setTheme('dark')}>Oscuro</Button><Button onClick={() => setTheme('light')}>Claro</Button><Button onClick={() => setTheme('sepia')}>Sepia</Button></div><label>Tamaño de letra: {font}px<input type="range" min="16" max="24" value={font} onChange={e => setFont(Number(e.target.value))}/></label></Card><Card><h3>Palabra diaria</h3><p>Te vamos a enviar una palabra diaria si das permiso. Podés desactivarlo cuando quieras.</p><Button onClick={() => Notification?.requestPermission?.()}>Pedir permiso</Button></Card><Card><h3>Licencia bíblica</h3><p>Palabra Viva utiliza textos bíblicos de dominio público o con licencia válida. No integrar traducciones modernas protegidas por derechos de autor sin la licencia correspondiente.</p></Card></div>}
    <nav className="bottom"><Nav icon={<Home/>} label="Hoy" active={tab==='hoy'} onClick={() => setTab('hoy')}/><Nav icon={<BookOpen/>} label="Biblia" active={tab==='biblia'} onClick={() => setTab('biblia')}/><Nav icon={<Heart/>} label="Sentir" active={tab==='sentir'} onClick={() => setTab('sentir')}/><Nav icon={<Search/>} label="Buscar" active={tab==='buscar'} onClick={() => setTab('buscar')}/><Nav icon={<CalendarDays/>} label="Planes" active={tab==='planes'} onClick={() => setTab('planes')}/></nav><div className="quick"><button onClick={() => setTab('guardado')}>Guardado</button><button onClick={() => setTab('oracion')}>Oración</button><button onClick={() => setTab('compartir')}>Compartir</button><button onClick={() => setTab('ajustes')}><Settings size={16}/></button></div></main>;
}
function titleFor(tab: Tab) { return ({ biblia:'Biblia', sentir:'¿Cómo te sentís?', buscar:'Buscar', planes:'Planes', oracion:'Oraciones', guardado:'Guardado', ajustes:'Ajustes', instalar:'Instalar app', compartir:'Compartir app', hoy:'Hoy' } as Record<Tab,string>)[tab]; }
function Nav({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active: boolean; onClick: () => void }) { return <button className={active ? 'nav active' : 'nav'} onClick={onClick}>{icon}<span>{label}</span></button>; }
createRoot(document.getElementById('root')!).render(<App />);
